modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "https://github.com/yisylvie/create-toolbox-tooltip/issues"
displayURL = "https://modrinth.com/mod/create-toolbox-tooltip/"
license = "MIT"

[[mods]]
modId = "createtoolboxtooltip"
version = "${version}"
displayName = "Create Toolbox Tooltip"
authors = "Sylvie Lee"
description = "What's in my toolbox?"
logoFile = "icon.png"

[[dependencies.createtoolboxtooltip]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.createtoolboxtooltip]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.createtoolboxtooltip]]
modId = "create"
mandatory = true
versionRange = "${create_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.createtoolboxtooltip]]
modId = "shulkerboxtooltip"
mandatory = true
versionRange = "${shulkerboxtooltip_version}"
ordering = "NONE"
side = "BOTH"