org.gradle.jvmargs = -Xmx2048M

# Mod Info
mod_name = Create Toolbox Tooltip
mod_id = createtoolboxtooltip
mod_version = 1.0.4
maven_group = com.yisylvie
mod_license = MIT
mod_url = https://modrinth.com/mod/create-toolbox-tooltip/
mod_issues_url = https://github.com/yisylvie/create-toolbox-tooltip/issues
mod_authors = Sylvie Lee
mod_description = What's in my toolbox?

minecraft_version = 1.21.1
enabled_platforms = neoforge

# https://github.com/neoforged/ModDevGradle?tab=readme-ov-file#better-minecraft-parameter-names--javadoc-parchment
# Find the latest versions at: https://parchmentmc.org/docs/getting-started
parchment_mappings_version = 2024.11.17

# NeoForge
# https://neoforged.net/
neo_version = 21.1.219
loader_version_range = [1,)

# Create - NeoForge
# https://wiki.createmod.net/developers/
create_neo_version = 6.0.9-215
registrate_neo_version = MC1.21-1.3.0+67
flywheel_neo_version = 1.0.6
ponder_neo_version = 1.0.81

# Shulker Box Tooltip
# https://modrinth.com/mod/shulkerboxtooltip/versions
shulkerboxtooltip_version = 5.1.9+1.21.1
# jankson
jankson_version=1.2.0


# Development QOL
# JEI - https://www.curseforge.com/minecraft/mc-mods/jei/files/all
jei_version = 19.27.0.340
