org.gradle.jvmargs = -Xmx2048M

# Mod Info
archives_base_name = createtoolboxtooltip
mod_version = 1.0.3
maven_group = com.yisylvie

minecraft_version = 1.21.1
enabled_platforms = neoforge

# Fabric
# https://fabricmc.net/develop
fabric_loader_version = 0.16.10

# NeoForge
# https://neoforged.net/
neo_version = 21.1.219

# Create - NeoForge
# https://wiki.createmod.net/developers/
create_neo_version = 6.0.9-215
registrate_neo_version = MC1.21-1.3.0+67
flywheel_neo_version = 1.0.6
ponder_neo_version = 1.0.81

# Shulker Box Tooltip
# https://modrinth.com/mod/shulkerboxtooltip/versions
shulkerboxtooltip_version = 5.1.9+1.21.1

# Development QOL
# Create Fabric supports all 3 recipe viewers: JEI, REI, and EMI. This decides which is enabled at runtime.
# set to disabled to have none of them.
fabric_recipe_viewer = EMI
# JEI - https://www.curseforge.com/minecraft/mc-mods/jei/files/all
jei_version = 19.27.0.340
# REI - https://modrinth.com/mod/rei/versions
rei_version = 12.0.626
# EMI - https://modrinth.com/mod/emi/versions
emi_version = 1.1.18+1.20.1
