org.gradle.jvmargs=-Xmx2G

# Mod Info
maven_group = com.yisylvie
archives_base_name = createtoolboxtooltip
mod_version = 0.1.0

minecraft_version = 1.20.1

# Dependencies
# https://fabricmc.net/develop
fabric_loader_version = 0.16.10
fabric_api_version = 0.92.3+1.20.1

# Mappings
# https://parchmentmc.org/docs/getting-started
parchment_version = 2023.09.03

# Create
# https://modrinth.com/mod/create-fabric/versions
create_version = 0.5.1-f-build.1417+mc1.20.1

#shulkerbox tooltip
shulkerboxtooltip_version = 4.0.4+1.20.1

#cloth config
cloth_config_api_version = 11.1.136

# Development QOL
# Create supports all 3 recipe viewers: JEI, REI, and EMI. This decides which is enabled at runtime.
# set to 'disabled' to have none of them.
recipe_viewer = EMI
# JEI - https://www.curseforge.com/minecraft/mc-mods/jei/files/all
jei_version = 15.2.0.22
# REI - https://modrinth.com/mod/rei/versions
rei_version = 12.0.626
# EMI - https://modrinth.com/mod/emi/versions
emi_version = 1.1.19+1.20.1

# Mod Menu - https://modrinth.com/mod/modmenu/versions
modmenu_version = 7.2.2
