architectury {
    common(rootProject.enabled_platforms.split(","))
}

loom {
    accessWidenerPath = file("src/main/resources/createtoolboxtooltip.accesswidener")
}

repositories {
}

dependencies {
    // We depend on fabric loader here to use the fabric @Environment annotations and get the mixin dependencies
    // Do NOT use other classes from fabric loader
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"

	// Compile against Create NeoForge in common
	// beware of differences across platforms!
	// dependencies must also be pulled in (transitively) for all classes to be remapped properly.
	// All dependencies except Flywheel and Registrate are NOT safe to use!
	// Flywheel and Registrate must also be used carefully due to differences across loaders.
	modCompileOnly("com.simibubi.create:create-${minecraft_version}:${create_neo_version}:slim") { transitive = false }
	implementation("com.tterrag.registrate:Registrate:${registrate_neo_version}")

	// Shulker Box Tooltip
    modImplementation("com.misterpemodder:shulkerboxtooltip-common:$shulkerboxtooltip_version") { transitive false }

	// Nullable annotations.
	implementation 'com.google.code.findbugs:jsr305:3.0.2'
	implementation 'org.jetbrains:annotations:23.0.0'
}
